---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"
    
- name: ensure profile.d directory exists
  become: yes
  become_user: root
  with_items:
    - '{{nss_pam_ldap_supervisord_profiled}}'
  file: >-
    path={{item}}
    state=directory
    mode=0755

- name: install boot scripts
  become: yes
  become_user: root
  with_items:
    - nslcd.sh
    - nscd.sh
  template: >-
    src={{item}}.j2
    dest={{nss_pam_ldap_supervisord_profiled}}/{{item}}
    mode=0755
